language: cpp

compiler:
  - gcc
  - clang

install:
  - git clone -b release-1.7.0 https://github.com/google/googletest.git
  - cd googletest
  - cmake -Dgtest_disable_pthreads=on .
  - cmake --build .
  - mkdir lib
  - mv libgtest* lib
  - cd ..

script:
  - cmake -DGTEST_ROOT=$PWD/googletest . && cmake --build . && ctest -V
  - ./benchmark 10

os:
  - linux
  - osx
