language: cpp

compiler:
  - gcc
  - clang

install:
  - git clone -b release-1.7.0 https://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - cmake --build .
  - mkdir lib
  - mv libgtest* lib
  - cd ..

script: cmake -DGTEST_ROOT=$PWD/googletest . && cmake --build . && ctest -V

os:
  - linux
  - osx
