language: cpp

compiler:
  - gcc
  - clang

install:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - cmake --build .
  - mkdir lib
  - mv libg* lib
  - export GTEST_ROOT=$PWD

before_script:
  - mkdir build
  - cd build

script: cmake .. && cmake --build . && ctest -V

os:
  - linux
  - osx
