language: cpp

compiler:
  - gcc
  - clang

install:
  - git clone -b release-1.7.0 https://github.com/google/googletest.git
  - cd googletest
  - cmake -Dgtest_disable_pthreads=on .
  - cmake --build .
  - mkdir lib
  - mv libgtest* lib
  - cd ..
  - hg clone https://bitbucket.org/eigen/eigen/ -r "3.2.7"
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-stdlib=libc++"; fi

script:
  - cmake -DGTEST_ROOT=$PWD/googletest -DEIGEN_INCLUDE=$PWD/eigen . && cmake --build . && ctest -V
  - ./benchmark 10

os:
  - linux
  - osx
