language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libgtest-dev

install:
  - apt-get install libgtest-dev
  - mkdir googletest
  - cd googletest
  - cmake /usr/src/gtest
  - cmake --build .
  - mkdir lib
  - mv libgtest* lib
  - cd ..

script: cmake -DGTEST_ROOT=$PWD/googletest . && cmake --build . && ctest -V

os:
  - linux
  - osx
